-- AlterTable
ALTER TABLE "files" ADD COLUMN     "name" TEXT;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "academic_degree" TEXT,
ADD COLUMN     "academic_status" TEXT,
ADD COLUMN     "academic_title" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "appointment_date" TIMESTAMP(3),
ADD COLUMN     "bio" TEXT,
ADD COLUMN     "birth_date" TIMESTAMP(3),
ADD COLUMN     "course" INTEGER,
ADD COLUMN     "department" TEXT,
ADD COLUMN     "dormitory" TEXT,
ADD COLUMN     "duties" TEXT,
ADD COLUMN     "education_level" TEXT,
ADD COLUMN     "employee_number" TEXT,
ADD COLUMN     "enrollment_year" INTEGER,
ADD COLUMN     "funding_type" TEXT,
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "gpa" DOUBLE PRECISION,
ADD COLUMN     "graduation_year" INTEGER,
ADD COLUMN     "headline" TEXT,
ADD COLUMN     "interests" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "job_title" TEXT,
ADD COLUMN     "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "middle_name" TEXT,
ADD COLUMN     "moderation_areas" TEXT,
ADD COLUMN     "office_hours" TEXT,
ADD COLUMN     "office_room" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "position" TEXT,
ADD COLUMN     "publications_url" TEXT,
ADD COLUMN     "research_interests" TEXT,
ADD COLUMN     "responsibilities" TEXT,
ADD COLUMN     "show_phone" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "specialty" TEXT,
ADD COLUMN     "starosta_since" TIMESTAMP(3),
ADD COLUMN     "student_card_number" TEXT,
ADD COLUMN     "study_form" TEXT,
ADD COLUMN     "subjects" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "telegram" TEXT,
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "website" TEXT,
ADD COLUMN     "work_phone" TEXT;

