// Справочник стран мира (ISO 3166-1): русское название + alpha-2 код (для флага flag-icons).
// Значение в профиле — русское название страны; code используется только для флага.

export interface CountryDictItem {
  value: string
  code: string
}

export const COUNTRIES_DICT: CountryDictItem[] = [
  { value: 'Австралия', code: 'au' },
  { value: 'Австрия', code: 'at' },
  { value: 'Азербайджан', code: 'az' },
  { value: 'Албания', code: 'al' },
  { value: 'Алжир', code: 'dz' },
  { value: 'Ангола', code: 'ao' },
  { value: 'Андорра', code: 'ad' },
  { value: 'Антигуа и Барбуда', code: 'ag' },
  { value: 'Аргентина', code: 'ar' },
  { value: 'Армения', code: 'am' },
  { value: 'Афганистан', code: 'af' },
  { value: 'Багамские Острова', code: 'bs' },
  { value: 'Бангладеш', code: 'bd' },
  { value: 'Барбадос', code: 'bb' },
  { value: 'Бахрейн', code: 'bh' },
  { value: 'Беларусь', code: 'by' },
  { value: 'Белиз', code: 'bz' },
  { value: 'Бельгия', code: 'be' },
  { value: 'Бенин', code: 'bj' },
  { value: 'Болгария', code: 'bg' },
  { value: 'Боливия', code: 'bo' },
  { value: 'Босния и Герцеговина', code: 'ba' },
  { value: 'Ботсвана', code: 'bw' },
  { value: 'Бразилия', code: 'br' },
  { value: 'Бруней', code: 'bn' },
  { value: 'Буркина-Фасо', code: 'bf' },
  { value: 'Бурунди', code: 'bi' },
  { value: 'Бутан', code: 'bt' },
  { value: 'Вануату', code: 'vu' },
  { value: 'Ватикан', code: 'va' },
  { value: 'Великобритания', code: 'gb' },
  { value: 'Венгрия', code: 'hu' },
  { value: 'Венесуэла', code: 've' },
  { value: 'Восточный Тимор', code: 'tl' },
  { value: 'Вьетнам', code: 'vn' },
  { value: 'Габон', code: 'ga' },
  { value: 'Гаити', code: 'ht' },
  { value: 'Гайана', code: 'gy' },
  { value: 'Гамбия', code: 'gm' },
  { value: 'Гана', code: 'gh' },
  { value: 'Гватемала', code: 'gt' },
  { value: 'Гвинея', code: 'gn' },
  { value: 'Гвинея-Бисау', code: 'gw' },
  { value: 'Германия', code: 'de' },
  { value: 'Гондурас', code: 'hn' },
  { value: 'Гренада', code: 'gd' },
  { value: 'Греция', code: 'gr' },
  { value: 'Грузия', code: 'ge' },
  { value: 'Дания', code: 'dk' },
  { value: 'Джибути', code: 'dj' },
  { value: 'Доминика', code: 'dm' },
  { value: 'Доминиканская Республика', code: 'do' },
  { value: 'Египет', code: 'eg' },
  { value: 'Замбия', code: 'zm' },
  { value: 'Зимбабве', code: 'zw' },
  { value: 'Израиль', code: 'il' },
  { value: 'Индия', code: 'in' },
  { value: 'Индонезия', code: 'id' },
  { value: 'Иордания', code: 'jo' },
  { value: 'Ирак', code: 'iq' },
  { value: 'Иран', code: 'ir' },
  { value: 'Ирландия', code: 'ie' },
  { value: 'Исландия', code: 'is' },
  { value: 'Испания', code: 'es' },
  { value: 'Италия', code: 'it' },
  { value: 'Йемен', code: 'ye' },
  { value: 'Кабо-Верде', code: 'cv' },
  { value: 'Казахстан', code: 'kz' },
  { value: 'Камбоджа', code: 'kh' },
  { value: 'Камерун', code: 'cm' },
  { value: 'Канада', code: 'ca' },
  { value: 'Катар', code: 'qa' },
  { value: 'Кения', code: 'ke' },
  { value: 'Кипр', code: 'cy' },
  { value: 'Киргизия', code: 'kg' },
  { value: 'Кирибати', code: 'ki' },
  { value: 'Китай', code: 'cn' },
  { value: 'КНДР (Северная Корея)', code: 'kp' },
  { value: 'Колумбия', code: 'co' },
  { value: 'Коморы', code: 'km' },
  { value: 'Конго (Республика)', code: 'cg' },
  { value: 'Конго (ДР)', code: 'cd' },
  { value: 'Коста-Рика', code: 'cr' },
  { value: 'Кот-д’Ивуар', code: 'ci' },
  { value: 'Куба', code: 'cu' },
  { value: 'Кувейт', code: 'kw' },
  { value: 'Лаос', code: 'la' },
  { value: 'Латвия', code: 'lv' },
  { value: 'Лесото', code: 'ls' },
  { value: 'Либерия', code: 'lr' },
  { value: 'Ливан', code: 'lb' },
  { value: 'Ливия', code: 'ly' },
  { value: 'Литва', code: 'lt' },
  { value: 'Лихтенштейн', code: 'li' },
  { value: 'Люксембург', code: 'lu' },
  { value: 'Маврикий', code: 'mu' },
  { value: 'Мавритания', code: 'mr' },
  { value: 'Мадагаскар', code: 'mg' },
  { value: 'Малави', code: 'mw' },
  { value: 'Малайзия', code: 'my' },
  { value: 'Мали', code: 'ml' },
  { value: 'Мальдивы', code: 'mv' },
  { value: 'Мальта', code: 'mt' },
  { value: 'Марокко', code: 'ma' },
  { value: 'Маршалловы Острова', code: 'mh' },
  { value: 'Мексика', code: 'mx' },
  { value: 'Мозамбик', code: 'mz' },
  { value: 'Молдавия', code: 'md' },
  { value: 'Монако', code: 'mc' },
  { value: 'Монголия', code: 'mn' },
  { value: 'Мьянма', code: 'mm' },
  { value: 'Намибия', code: 'na' },
  { value: 'Науру', code: 'nr' },
  { value: 'Непал', code: 'np' },
  { value: 'Нигер', code: 'ne' },
  { value: 'Нигерия', code: 'ng' },
  { value: 'Нидерланды', code: 'nl' },
  { value: 'Никарагуа', code: 'ni' },
  { value: 'Новая Зеландия', code: 'nz' },
  { value: 'Норвегия', code: 'no' },
  { value: 'ОАЭ', code: 'ae' },
  { value: 'Оман', code: 'om' },
  { value: 'Пакистан', code: 'pk' },
  { value: 'Палау', code: 'pw' },
  { value: 'Панама', code: 'pa' },
  { value: 'Папуа — Новая Гвинея', code: 'pg' },
  { value: 'Парагвай', code: 'py' },
  { value: 'Перу', code: 'pe' },
  { value: 'Польша', code: 'pl' },
  { value: 'Португалия', code: 'pt' },
  { value: 'Россия', code: 'ru' },
  { value: 'Руанда', code: 'rw' },
  { value: 'Румыния', code: 'ro' },
  { value: 'Сальвадор', code: 'sv' },
  { value: 'Самоа', code: 'ws' },
  { value: 'Сан-Марино', code: 'sm' },
  { value: 'Сан-Томе и Принсипи', code: 'st' },
  { value: 'Саудовская Аравия', code: 'sa' },
  { value: 'Северная Македония', code: 'mk' },
  { value: 'Сейшельские Острова', code: 'sc' },
  { value: 'Сенегал', code: 'sn' },
  { value: 'Сент-Винсент и Гренадины', code: 'vc' },
  { value: 'Сент-Китс и Невис', code: 'kn' },
  { value: 'Сент-Люсия', code: 'lc' },
  { value: 'Сербия', code: 'rs' },
  { value: 'Сингапур', code: 'sg' },
  { value: 'Сирия', code: 'sy' },
  { value: 'Словакия', code: 'sk' },
  { value: 'Словения', code: 'si' },
  { value: 'Соломоновы Острова', code: 'sb' },
  { value: 'Сомали', code: 'so' },
  { value: 'Судан', code: 'sd' },
  { value: 'Суринам', code: 'sr' },
  { value: 'США', code: 'us' },
  { value: 'Сьерра-Леоне', code: 'sl' },
  { value: 'Таджикистан', code: 'tj' },
  { value: 'Таиланд', code: 'th' },
  { value: 'Танзания', code: 'tz' },
  { value: 'Того', code: 'tg' },
  { value: 'Тонга', code: 'to' },
  { value: 'Тринидад и Тобаго', code: 'tt' },
  { value: 'Тувалу', code: 'tv' },
  { value: 'Тунис', code: 'tn' },
  { value: 'Туркмения', code: 'tm' },
  { value: 'Турция', code: 'tr' },
  { value: 'Уганда', code: 'ug' },
  { value: 'Узбекистан', code: 'uz' },
  { value: 'Украина', code: 'ua' },
  { value: 'Уругвай', code: 'uy' },
  { value: 'Фиджи', code: 'fj' },
  { value: 'Филиппины', code: 'ph' },
  { value: 'Финляндия', code: 'fi' },
  { value: 'Франция', code: 'fr' },
  { value: 'Хорватия', code: 'hr' },
  { value: 'ЦАР', code: 'cf' },
  { value: 'Чад', code: 'td' },
  { value: 'Черногория', code: 'me' },
  { value: 'Чехия', code: 'cz' },
  { value: 'Чили', code: 'cl' },
  { value: 'Швейцария', code: 'ch' },
  { value: 'Швеция', code: 'se' },
  { value: 'Шри-Ланка', code: 'lk' },
  { value: 'Эквадор', code: 'ec' },
  { value: 'Экваториальная Гвинея', code: 'gq' },
  { value: 'Эритрея', code: 'er' },
  { value: 'Эсватини', code: 'sz' },
  { value: 'Эстония', code: 'ee' },
  { value: 'Эфиопия', code: 'et' },
  { value: 'ЮАР', code: 'za' },
  { value: 'Южная Корея', code: 'kr' },
  { value: 'Южный Судан', code: 'ss' },
  { value: 'Ямайка', code: 'jm' },
  { value: 'Япония', code: 'jp' },
]

export const COUNTRY_VALUES: string[] = COUNTRIES_DICT.map((c) => c.value)

const COUNTRY_CODE_BY_VALUE = new Map(
  COUNTRIES_DICT.map((c) => [c.value.trim().toLowerCase(), c.code]),
)

// alpha-2 код страны по её названию (как хранится в профиле); null — нет в справочнике.
export function countryCodeOf(value: string): string | null {
  return COUNTRY_CODE_BY_VALUE.get(value.trim().toLowerCase()) ?? null
}
