// Справочник навыков (~600) по разным направлениям. Значения = что сохраняется в профиль.
// Вне списка допускается свой ввод. Держим плоским массивом; порядок роли не играет (поиск в UI).

export const SKILLS_DICT: string[] = [
  // ── Языки программирования ──
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C',
  'C++',
  'C#',
  'Go',
  'Rust',
  'Kotlin',
  'Swift',
  'Objective-C',
  'PHP',
  'Ruby',
  'Scala',
  'Dart',
  'Elixir',
  'Erlang',
  'Haskell',
  'Clojure',
  'F#',
  'Perl',
  'Lua',
  'R',
  'MATLAB',
  'Julia',
  'Groovy',
  'Visual Basic',
  'Assembly',
  'COBOL',
  'Fortran',
  'Solidity',
  'Zig',
  'Nim',
  'Crystal',
  'OCaml',
  'Scheme',
  'Prolog',
  'Bash',
  'PowerShell',
  // ── Frontend ──
  'HTML',
  'CSS',
  'Sass',
  'Less',
  'Tailwind CSS',
  'Bootstrap',
  'React',
  'Next.js',
  'Vue',
  'Nuxt',
  'Angular',
  'Svelte',
  'SvelteKit',
  'SolidJS',
  'Redux',
  'Redux Toolkit',
  'MobX',
  'Zustand',
  'RxJS',
  'jQuery',
  'Webpack',
  'Vite',
  'Rollup',
  'Babel',
  'ESLint',
  'Prettier',
  'Storybook',
  'Web Components',
  'PWA',
  'WebAssembly',
  'Three.js',
  'D3.js',
  'Canvas API',
  'WebGL',
  'Accessibility (a11y)',
  'Responsive Design',
  'Framer Motion',
  'Material UI',
  'Chakra UI',
  'shadcn/ui',
  // ── Backend ──
  'Node.js',
  'Express',
  'NestJS',
  'Fastify',
  'Koa',
  'Django',
  'Flask',
  'FastAPI',
  'Spring',
  'Spring Boot',
  'Laravel',
  'Symfony',
  'Ruby on Rails',
  'ASP.NET',
  'ASP.NET Core',
  '.NET',
  'Gin',
  'Fiber',
  'Actix',
  'Phoenix',
  'GraphQL',
  'REST API',
  'gRPC',
  'WebSocket',
  'Microservices',
  'Message Queues',
  'RabbitMQ',
  'Kafka',
  'BullMQ',
  'Celery',
  'OAuth 2.0',
  'JWT',
  'OpenAPI / Swagger',
  'API Design',
  'Serverless',
  'Event-Driven Architecture',
  'DDD',
  'CQRS',
  'Clean Architecture',
  'Monorepo',
  // ── Мобильная разработка ──
  'React Native',
  'Flutter',
  'SwiftUI',
  'UIKit',
  'Jetpack Compose',
  'Android SDK',
  'iOS Development',
  'Xamarin',
  'Ionic',
  'Expo',
  // ── Базы данных ──
  'SQL',
  'PostgreSQL',
  'MySQL',
  'MariaDB',
  'SQLite',
  'Oracle',
  'SQL Server',
  'MongoDB',
  'Redis',
  'Cassandra',
  'Elasticsearch',
  'DynamoDB',
  'Firebase',
  'Supabase',
  'Neo4j',
  'ClickHouse',
  'Prisma',
  'TypeORM',
  'Sequelize',
  'Drizzle',
  'Database Design',
  'Query Optimization',
  'Data Modeling',
  'Database Administration',
  'ETL',
  // ── DevOps / Cloud / Infra ──
  'Git',
  'GitHub',
  'GitLab',
  'Docker',
  'Kubernetes',
  'Helm',
  'Terraform',
  'Ansible',
  'Linux',
  'Nginx',
  'Apache',
  'CI/CD',
  'GitHub Actions',
  'GitLab CI',
  'Jenkins',
  'AWS',
  'Google Cloud',
  'Microsoft Azure',
  'DigitalOcean',
  'Cloudflare',
  'Prometheus',
  'Grafana',
  'ELK Stack',
  'Datadog',
  'Sentry',
  'MinIO',
  'S3',
  'Load Balancing',
  'CDN',
  'Monitoring',
  'Bash Scripting',
  'Networking',
  'DNS',
  'TCP/IP',
  'VPN',
  'Virtualization',
  'Vagrant',
  'Site Reliability Engineering',
  'Infrastructure as Code',
  'GitOps',
  // ── Data / ML / AI ──
  'Machine Learning',
  'Deep Learning',
  'Neural Networks',
  'Computer Vision',
  'NLP',
  'LLM',
  'Prompt Engineering',
  'PyTorch',
  'TensorFlow',
  'Keras',
  'scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Jupyter',
  'Data Analysis',
  'Data Science',
  'Data Engineering',
  'Big Data',
  'Apache Spark',
  'Hadoop',
  'Airflow',
  'Data Visualization',
  'Statistics',
  'A/B Testing',
  'Recommendation Systems',
  'Time Series',
  'MLOps',
  'Hugging Face',
  'OpenCV',
  'Power BI',
  'Tableau',
  'Looker',
  'Google Analytics',
  'Excel',
  // ── Безопасность ──
  'Cybersecurity',
  'Penetration Testing',
  'Ethical Hacking',
  'Network Security',
  'Cryptography',
  'OWASP',
  'Reverse Engineering',
  'Malware Analysis',
  'Incident Response',
  'Security Auditing',
  'SIEM',
  'Firewall Configuration',
  'Vulnerability Assessment',
  'Threat Modeling',
  'Digital Forensics',
  // ── QA / Тестирование ──
  'Manual Testing',
  'Automated Testing',
  'Unit Testing',
  'Integration Testing',
  'E2E Testing',
  'Jest',
  'Vitest',
  'Playwright',
  'Cypress',
  'Selenium',
  'Test Planning',
  'Bug Tracking',
  'Load Testing',
  'Performance Testing',
  'TDD',
  'BDD',
  'Postman',
  'JMeter',
  'QA Automation',
  'Regression Testing',
  // ── Дизайн / UX ──
  'UI Design',
  'UX Design',
  'Product Design',
  'Figma',
  'Sketch',
  'Adobe XD',
  'Photoshop',
  'Illustrator',
  'InDesign',
  'After Effects',
  'Premiere Pro',
  'Blender',
  'Cinema 4D',
  '3D Modeling',
  'Motion Design',
  'Prototyping',
  'Wireframing',
  'Design Systems',
  'Typography',
  'Color Theory',
  'User Research',
  'Usability Testing',
  'Interaction Design',
  'Graphic Design',
  'Branding',
  'Logo Design',
  'Icon Design',
  'Illustration',
  'Web Design',
  'Design Thinking',
  // ── Продукт / Менеджмент ──
  'Product Management',
  'Project Management',
  'Agile',
  'Scrum',
  'Kanban',
  'Jira',
  'Confluence',
  'Trello',
  'Notion',
  'Roadmapping',
  'Backlog Management',
  'Stakeholder Management',
  'Business Analysis',
  'Requirements Gathering',
  'User Stories',
  'OKR',
  'Product Strategy',
  'Team Leadership',
  'People Management',
  'Risk Management',
  'Time Management',
  'Budgeting',
  'Resource Planning',
  'Change Management',
  'Process Improvement',
  'Lean',
  'Six Sigma',
  'PRINCE2',
  'PMP',
  'Product Analytics',
  // ── Маркетинг / SMM / Контент ──
  'Digital Marketing',
  'SEO',
  'SEM',
  'Content Marketing',
  'Copywriting',
  'Email Marketing',
  'Social Media Marketing',
  'SMM',
  'Google Ads',
  'Meta Ads',
  'Marketing Analytics',
  'Brand Management',
  'PR',
  'Influencer Marketing',
  'Growth Hacking',
  'CRM',
  'HubSpot',
  'Mailchimp',
  'Content Strategy',
  'Community Management',
  'Video Editing',
  'Podcasting',
  'Storytelling',
  'Technical Writing',
  'Blogging',
  'Marketing Automation',
  'Conversion Optimization',
  'Market Research',
  'Advertising',
  'Media Planning',
  // ── Финансы / Бизнес / Право ──
  'Accounting',
  'Financial Analysis',
  'Financial Modeling',
  'Bookkeeping',
  'Auditing',
  'Taxation',
  'Investment Analysis',
  'Valuation',
  'Budget Planning',
  'Payroll',
  'Economics',
  'Business Development',
  'Sales',
  'Negotiation',
  'B2B Sales',
  'Account Management',
  'Entrepreneurship',
  'Startup',
  'Fundraising',
  'Business Strategy',
  'Contract Law',
  'Corporate Law',
  'Legal Research',
  'Compliance',
  'Intellectual Property',
  'GDPR',
  'Legal Writing',
  'Mediation',
  'Due Diligence',
  'Risk Assessment',
  '1C',
  'SAP',
  'QuickBooks',
  'Financial Reporting',
  'Cost Management',
  // ── Инженерия / Наука ──
  'AutoCAD',
  'SolidWorks',
  'Revit',
  'CATIA',
  'KOMPAS-3D',
  'MATLAB Simulink',
  'Circuit Design',
  'PCB Design',
  'Embedded Systems',
  'Arduino',
  'Raspberry Pi',
  'Robotics',
  'PLC Programming',
  'CNC',
  '3D Printing',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Civil Engineering',
  'Structural Analysis',
  'CAD',
  'Thermodynamics',
  'Fluid Mechanics',
  'Signal Processing',
  'Control Systems',
  'IoT',
  'GIS',
  'Surveying',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Calculus',
  'Linear Algebra',
  'Probability',
  'Discrete Math',
  'Numerical Methods',
  // ── Медицина / Здоровье ──
  'First Aid',
  'Anatomy',
  'Physiology',
  'Pharmacology',
  'Nursing',
  'Patient Care',
  'Medical Diagnosis',
  'Clinical Research',
  'Public Health',
  'Epidemiology',
  'Nutrition',
  'Physical Therapy',
  'Mental Health',
  'Psychology',
  'Counseling',
  'Medical Coding',
  'Laboratory Skills',
  'Radiology',
  'Surgery Assistance',
  'Telemedicine',
  // ── Образование / Гуманитарные ──
  'Teaching',
  'Curriculum Development',
  'Lesson Planning',
  'Tutoring',
  'Public Speaking',
  'Presentation Skills',
  'Mentoring',
  'E-learning',
  'Instructional Design',
  'Academic Writing',
  'Research',
  'Translation',
  'Interpreting',
  'Proofreading',
  'Editing',
  'Linguistics',
  'History',
  'Philosophy',
  'Sociology',
  'Political Science',
  // ── Творчество / Медиа ──
  'Photography',
  'Videography',
  'Cinematography',
  'Sound Design',
  'Music Production',
  'Audio Editing',
  'DJing',
  'Songwriting',
  'Screenwriting',
  'Animation',
  '2D Animation',
  '3D Animation',
  'Game Design',
  'Game Development',
  'Unity',
  'Unreal Engine',
  'Godot',
  'Level Design',
  'Concept Art',
  'Digital Painting',
  // ── Офис / Инструменты / Прочее ──
  'Microsoft Office',
  'Word',
  'PowerPoint',
  'Google Workspace',
  'Google Sheets',
  'Data Entry',
  'Customer Support',
  'Technical Support',
  'Help Desk',
  'CRM Administration',
  'Event Management',
  'Logistics',
  'Supply Chain',
  'Procurement',
  'Inventory Management',
  'Quality Control',
  'Lean Manufacturing',
  'HR',
  'Recruiting',
  'Onboarding',
  // ── Soft skills ──
  'Communication',
  'Teamwork',
  'Leadership',
  'Critical Thinking',
  'Problem Solving',
  'Creativity',
  'Adaptability',
  'Emotional Intelligence',
  'Conflict Resolution',
  'Decision Making',
  'Collaboration',
  'Attention to Detail',
  'Self-Management',
  'Work Ethic',
  'Empathy',
  'Active Listening',
  'Multitasking',
  'Analytical Thinking',
  'Networking',
  'Resilience',
]
