-- CreateEnum
CREATE TYPE "Role" AS ENUM ('PLATFORM_ADMIN', 'PLATFORM_MODERATOR', 'UNIVERSITY_ADMIN', 'UNIVERSITY_MODERATOR', 'DEAN', 'TEACHER', 'STAROSTA', 'STUDENT');

-- CreateEnum
CREATE TYPE "UniversityStatus" AS ENUM ('PENDING', 'ACTIVE', 'BLOCKED');

-- CreateEnum
CREATE TYPE "InviteStatus" AS ENUM ('PENDING', 'USED', 'EXPIRED', 'REVOKED');

-- CreateEnum
CREATE TYPE "ApplicationStatus" AS ENUM ('NEW', 'PROCESSING', 'CLARIFICATION', 'APPROVED', 'REJECTED', 'READY', 'CLOSED');

-- CreateEnum
CREATE TYPE "AppType" AS ENUM ('CERTIFICATE', 'MILITARY', 'UNIVERSAL', 'ACADEMIC', 'FINANCIAL', 'TECHNICAL', 'OTHER');

-- CreateEnum
CREATE TYPE "PostAudience" AS ENUM ('ALL', 'UNIVERSITY', 'FACULTY', 'GROUP', 'SUBJECT', 'TEACHERS', 'PERSONAL');

-- CreateEnum
CREATE TYPE "ChatType" AS ENUM ('PRIVATE', 'GROUP', 'GROUP_OFFICIAL', 'SUBJECT', 'FACULTY', 'DEAN', 'SUPPORT', 'EVENT');

-- CreateEnum
CREATE TYPE "WeekType" AS ENUM ('ODD', 'EVEN', 'BOTH');

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('SCHEDULE_CHANGE', 'APP_UPDATE', 'MESSAGE', 'POST', 'EVENT', 'SYSTEM');

-- CreateEnum
CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP', 'EMAIL', 'PUSH');

-- CreateEnum
CREATE TYPE "ScheduleChangeType" AS ENUM ('MOVED', 'ROOM_CHANGED', 'CANCELLED', 'SUBSTITUTED');

-- CreateEnum
CREATE TYPE "ComplaintTargetType" AS ENUM ('POST', 'STORY', 'COMMENT', 'MESSAGE', 'USER');

-- CreateEnum
CREATE TYPE "ComplaintStatus" AS ENUM ('PENDING', 'REVIEWING', 'RESOLVED', 'DISMISSED');
