export enum ErrorCode {
  // Authentication
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TWO_FACTOR_REQUIRED = 'AUTH_TWO_FACTOR_REQUIRED',
  AUTH_TWO_FACTOR_INVALID = 'AUTH_TWO_FACTOR_INVALID',
  AUTH_PASSWORD_TOO_WEAK = 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_SAME_PASSWORD = 'AUTH_SAME_PASSWORD',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_TWO_FACTOR_ALREADY_ENABLED = 'AUTH_TWO_FACTOR_ALREADY_ENABLED',
  AUTH_TWO_FACTOR_NOT_ENABLED = 'AUTH_TWO_FACTOR_NOT_ENABLED',
  AUTH_TWO_FACTOR_SETUP_EXPIRED = 'AUTH_TWO_FACTOR_SETUP_EXPIRED',
  AUTH_TOKEN_BLACKLISTED = 'AUTH_TOKEN_BLACKLISTED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_FIELD_REQUIRED = 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID = 'VALIDATION_FIELD_INVALID',
  VALIDATION_INVALID_VERIFICATION_CODE = 'VALIDATION_INVALID_VERIFICATION_CODE',

  // Resources
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_ACCESS_DENIED = 'RESOURCE_ACCESS_DENIED',

  // Business Logic
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',

  // Server
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 'Invalid credentials',
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 'Token expired',
  [ErrorCode.AUTH_TOKEN_INVALID]: 'Invalid token',
  [ErrorCode.AUTH_REQUIRED]: 'Authentication required',
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: 'Email not verified',
  [ErrorCode.AUTH_TWO_FACTOR_REQUIRED]: 'Two-factor authentication required',
  [ErrorCode.AUTH_TWO_FACTOR_INVALID]: 'Invalid two-factor code',
  [ErrorCode.AUTH_PASSWORD_TOO_WEAK]: 'Password too weak',
  [ErrorCode.AUTH_SAME_PASSWORD]: 'New password must be different from current',
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 'Account locked',
  [ErrorCode.AUTH_TWO_FACTOR_ALREADY_ENABLED]: 'Two-factor authentication already enabled',
  [ErrorCode.AUTH_TWO_FACTOR_NOT_ENABLED]: 'Two-factor authentication not enabled',
  [ErrorCode.AUTH_TWO_FACTOR_SETUP_EXPIRED]: 'Two-factor setup expired',
  [ErrorCode.AUTH_TOKEN_BLACKLISTED]: 'Token blacklisted',
  [ErrorCode.AUTH_INVALID_TOKEN]: 'Invalid token',

  [ErrorCode.VALIDATION_ERROR]: 'Validation error',
  [ErrorCode.VALIDATION_FIELD_REQUIRED]: 'Field is required',
  [ErrorCode.VALIDATION_FIELD_INVALID]: 'Field is invalid',
  [ErrorCode.VALIDATION_INVALID_VERIFICATION_CODE]: 'Invalid or expired verification code',

  [ErrorCode.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ErrorCode.RESOURCE_ACCESS_DENIED]: 'Access denied',

  [ErrorCode.BUSINESS_RULE_VIOLATION]: 'Business rule violation',
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ErrorCode.OPERATION_NOT_ALLOWED]: 'Operation not allowed',

  [ErrorCode.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ErrorCode.SERVICE_UNAVAILABLE]: 'Service unavailable',
};
