export {
  analyticsKeys,
  fetchFacultyOverview,
  fetchGroupAttendance,
  fetchAtRiskStudents,
  platformAnalyticsKeys,
  fetchPlatformOverview,
  fetchUsersGrowth,
  fetchActiveUsers,
  fetchUniversitiesSize,
  fetchComplaintsFlow,
  fetchComplaintsLatency,
  fetchInvitesFunnel,
  fetchActivityHeatmap,
  fetchTopActions,
  type PlatformRange,
} from './api/analytics-api'
export type {
  FacultyOverview,
  FacultyTotals,
  GroupStat,
  AtRiskGroup,
  GroupAttendance,
  StudentAttendanceStat,
  AtRiskStudent,
  AtRiskStudents,
  RiskReason,
  RiskReasonKind,
  PlatformInterval,
  SeriesPoint,
  MultiSeries,
  PlatformOverview,
  UniversitySize,
  ComplaintsLatency,
  InvitesFunnel,
  ActivityHeatmap,
  TopActions,
} from './model/types'
