// @studenthub/shared-schemas — Zod-схемы, единый источник валидации (API + формы).

export * from './auth.js'
export * from './invites.js'
export * from './users.js'
export * from './pagination.js'
export * from './files.js'
export * from './universities.js'
export * from './faculties.js'
export * from './specialties.js'
export * from './groups.js'
export * from './rooms.js'
export * from './schedule.js'
export * from './application-services.js'
export * from './posts.js'
export * from './chats.js'
export * from './events.js'
export * from './complaints.js'
export * from './audit.js'
export * from './materials.js'
export * from './notifications.js'
export * from './profile.js'
export * from './documents.js'
export * from './friends.js'
