export {
  courseKeys,
  fetchCourses,
  fetchCoursesPaged,
  fetchTermsPaged,
  fetchSubjectsPaged,
  fetchCourse,
  fetchSubjects,
  fetchTerms,
  createSubjectRequest,
  deleteSubjectRequest,
  createTermRequest,
  deleteTermRequest,
  createCourseRequest,
  updateCourseRequest,
  deleteCourseRequest,
} from './api/course-api'
export type {
  CourseItem,
  SubjectItem,
  TermItem,
  CourseSubjectRef,
  CourseGroupRef,
  CourseTeacherRef,
  CourseTermRef,
} from './model/types'
